// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVjBqjx9tfoc0HSFHcKgNO9IekPjhkYc',
    appId: '1:38387700535:web:4a54c9dcd4e587937d80b2',
    messagingSenderId: '38387700535',
    projectId: 'praktyki-szkolne',
    authDomain: 'praktyki-szkolne.firebaseapp.com',
    databaseURL: 'https://praktyki-szkolne-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praktyki-szkolne.appspot.com',
    measurementId: 'G-HL833H7G44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-iZk4gYYy7TO8qGW7e-SgBoXzTvg6-Wo',
    appId: '1:38387700535:android:f5a8cc3f7327dfe17d80b2',
    messagingSenderId: '38387700535',
    projectId: 'praktyki-szkolne',
    databaseURL: 'https://praktyki-szkolne-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praktyki-szkolne.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCIfCGDrDmDsSuHRQVRUajmQi4D6OXFks',
    appId: '1:38387700535:ios:737b8739f3cb91e47d80b2',
    messagingSenderId: '38387700535',
    projectId: 'praktyki-szkolne',
    databaseURL: 'https://praktyki-szkolne-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praktyki-szkolne.appspot.com',
    androidClientId: '38387700535-jef7a6hkc41mki0f0hnfdou63ts2b41g.apps.googleusercontent.com',
    iosClientId: '38387700535-vjocdhktvc6rio7jgcmvpp1onr8p4lnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.prakty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCIfCGDrDmDsSuHRQVRUajmQi4D6OXFks',
    appId: '1:38387700535:ios:1b68ec62977946f77d80b2',
    messagingSenderId: '38387700535',
    projectId: 'praktyki-szkolne',
    databaseURL: 'https://praktyki-szkolne-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'praktyki-szkolne.appspot.com',
    androidClientId: '38387700535-jef7a6hkc41mki0f0hnfdou63ts2b41g.apps.googleusercontent.com',
    iosClientId: '38387700535-6thftha5cthu64j71doim6n6vf1ac3rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prakty.RunnerTests',
  );
}
